server:
  port: 8081
  servlet:
    context-path: /api
spring:
  profiles:
    active: in_memory
  cache:
    cache-names:
      - rate-limit-buckets-widget
      - rate-limit-buckets-widgets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets-widget
      url: /api/widget(/\d+)?
      rate-limits:
        - bandwidths:
            - capacity: 10
              time: 1
              unit: minutes
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes
    - cache-name: rate-limit-buckets-widgets
      url: /api/widgets
      rate-limits:
        - bandwidths:
            - capacity: 2
              time: 1
              unit: minutes
              fixed-refill-interval: 1
              fixed-refill-interval-unit: minutes
